name: Waypoint
main: me.pirogoeth.Waypoint.Waypoint
version: 1.5.3
author: pirogoeth
commands:
    wp:
        description: Manage waypoints for yourself.
        usage: /wp <add|del|tp;list> [name]
        aliases: 
            - waypoint
        permission: waypoint.basic
    home:
        description: Save your home location.
        usage: /home [add]
        aliases: 
            - home
        permission: waypoint.home
    world:
        description: Display your current world and position or teleport between worlds.
        usage: /world [worldname]
        aliases:
            - wpworld
        permissions: waypoint.world
    spawn:
        description: Teleport to world spawn points.
        usage: /spawn <world>
        aliases:
            - wpspawn
        permission: waypoint.spawn
    setspawn:
        description: Shortcut for /spawnadmin set
        usage: /setspawn
        aliases:
            - wpsetspawn
        permission: waypoint.admin.spawn.set
    setwarp:
        description: Shortcut for /warp add
        usage: /setwarp <name>
        aliases:
            - wpsetwarp
        permission: waypoint.warp.create
    spawnadmin:
        description: Manage spawn details.
        usage: /spawnadmin <save|load;set> [world]
        aliases:
            - wpspawnadmin
        permission: waypoint.admin.spawn
    warp:
        description: Manage public warps.
        usage: /warp <add|del|set|list|<or warpname>> <warpname or key:value>
        aliases:
            - wpwarp
        permission: waypoint.warp
    warpadmin:
        description: Manage warps.
        usage: /warpadmin <set|del> <warp> [key] [value]
        aliases:
            - wpwarpadmin
        permission: waypoint.admin.warp
    tp:
        description: Teleport to another user/another user to you.
        usage: /tp <user> [target]
        aliases: 
            - wptp
        permission: waypoint.teleport
    tphere:
        description: Teleport a user to you.
        usage: /tphere <user>
        aliases: 
            - wptphere
        permission: waypoint.teleport.here
    tploc:
        descript: Allows you to teleport to a set of coordinates.
        usage: /tploc <x,y,z>
        aliases:
            - wptploc
        permission: waypoint.teleport.location