name: Waypoint
main: me.pirogoeth.Waypoint.Waypoint
version: 1.6.5
author: pirogoeth
softdepend: [Vault]
order: startup
commands:
    wp:
        description: Manage waypoints for yourself.
        usage: /wp <add|del|tp;list> [name]
        aliases: 
            - waypoint
    home:
        description: Save your home location.
        usage: /home [add]
        aliases: 
            - wphome
    world:
        description: Display your current world and position or teleport between worlds.
        usage: /world [worldname]
        aliases:
            - wpworld
    spawn:
        description: Teleport to world spawn points.
        usage: /spawn <world>
        aliases:
            - wpspawn
    setspawn:
        description: Shortcut for /spawnadmin set
        usage: /setspawn
        aliases:
            - wpsetspawn
    setwarp:
        description: Shortcut for /warp add
        usage: /setwarp <name>
        aliases:
            - wpsetwarp
    spawnadmin:
        description: Manage spawn details.
        usage: /spawnadmin <save|load;set> [world]
        aliases:
            - wpspawnadmin
    warp:
        description: Manage public warps.
        usage: /warp <add|del|set|list|<or warpname>> <warpname or key:value>
        aliases:
            - wpwarp
    warpadmin:
        description: Manage warps.
        usage: /warpadmin <set|del> <warp> [key] [value]
        aliases:
            - wpwarpadmin
    tp:
        description: Teleport to another user/another user to you.
        usage: /tp <user> [target]
        aliases: 
            - wptp
    tphere:
        description: Teleport a user to you.
        usage: /tphere <user>
        aliases: 
            - wptphere
    tploc:
        descript: Allows you to teleport to a set of coordinates.
        usage: /tploc <x,y,z>
        aliases:
            - wptploc